# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ba8e2c2ac08a75b33bf508680b4df374b4179561963dd60cc11cffdf856a1a7d422c5cee10f7ee146b3716745bf9f8c4d7d0219819c0c2c8c8b30b120540465

test:
  secret_key_base: 96671bb8dc927b2f46d08433ea6199a73ca0d00803898f2240a87db5003941f6bd980e2731991612441087f46204a5aa391abcd7f2439205dd6f49c328ad8f59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
